### ISSUE TITLE
Achievement screen crashes after updating

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#39]
I recently updated Pixture to dec846e26507f14c30a35d16cc2fa70f967d8417 and whenever I open the achievements screen, I get this:

```2017-05-12 14:19:38: ERROR[Main]: ServerError: Lua: Runtime error from mod 'default' in callback on_playerReceiveFields(): ...wuzzy/.minetest/games/pixture/mods/achievements/init.lua:193: attempt to index a nil value
2017-05-12 14:19:38: ERROR[Main]: stack traceback:
2017-05-12 14:19:38: ERROR[Main]: 	...wuzzy/.minetest/games/pixture/mods/achievements/init.lua:193: in function 'get_formspec'
2017-05-12 14:19:38: ERROR[Main]: 	.../wuzzy/.minetest/games/pixture/mods/default/formspec.lua:246: in function 'receive_fields'
2017-05-12 14:19:38: ERROR[Main]: 	.../wuzzy/.minetest/games/pixture/mods/default/formspec.lua:254: in function <.../wuzzy/.minetest/games/pixture/mods/default/formspec.lua:253>
2017-05-12 14:19:38: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:412: in function </usr/share/minetest/builtin/game/register.lua:392>
```

Note that I use a world which I have since a couple of months. Backwards-compability, anyone?

**Comment by kaadmy** [comment]
Backwards compatibility will very likely be broken, or at the very least act strange.
Achievements have that problem now since I changed stuff and the achievements file wasn't written correctly on shutdown.

**Edit:** this will happen to an older world that has been opened since I "fixed" the problem, will add in a patch soon since this is fixable.

**Edit2:** huh, it looks like I check everything correctly already... I'll leave this open for now since it only happens on older worlds anyway.

**Comment by Wuzzy2** [comment]
Thanks. In case you feel unable to fix this, for some reason, just tell me how I can repair my world.

**Comment by kaadmy** [comment]
You *should* be able to fix it by adding

```
return {["Wuzzy"] = {}}
```

To the `<world>/achievements` file
But not tested, you might want to backup your world JIC.

**Comment by kaadmy** [comment]
I'll close this now since I can't do much about this since it's a bug with older versions incorrectly saving achievements.

**Comment by Wuzzy2** [comment]
Okay. I guess I just start over with the achievements instead of losing my world.

**Comment by kaadmy** [comment]
If you know roughly what your achievements were, then you should be able to just put in placeholders that are about correct to save you time farming thousands of blocks ;)

**Comment by asl97** [comment]
@Wuzzy2 Your issue report lack the error, is it an `attempt to index a nil value`?
The achievement file name was just changed, https://github.com/kaadmy/pixture/commit/3f26b5431d52ffc561a82cee0b48c5e966d3e793

From the looks of things, the save format hasn't changed that much.
You can try just changing the name of the save file and see if that works.

It works for me, you should notice there are a bunch of dat file in the world folder.
____
@kaadmy Honestly, should have really done some backward compatibility like check if the old file exist, then try to load it, if it load successfully, rename it to the new name, otherwise throw an error so the admin knows something is wrong with their world and have to manually fix it.

**Comment by kaadmy** [comment]
Well first of all the issue was that the old achievements file didn't correctly write on some occasions, not that it wasn't loading correctly...

**Comment by kaadmy** [comment]
Hm, I see what you mean
Anyway, although I probably should have announced that I'm ignoring backwards compatibility for now until I release 0.1.0, since I'm changing a lot of pretty major things.

**Comment by asl97** [comment]
The issue was unknown, the log that @Wuzzy2 provided doesn't says it loaded it or not.
I have a working world with properly saved achievement and I get the same error after updating to the commit.

**Comment by kaadmy** [comment]
Ah okay, thanks for clarifying that.

**Comment by asl97** [comment]
@Wuzzy2 Forgot to mention, what @kaadmy [suggested](https://github.com/kaadmy/pixture/issues/39#issuecomment-301087460) wouldn't work if there are other players, you have to dummy out every single player or you get the same error.

This is due to the fact that it only initialize the player achievement when they are a new player and not when they are joining the server.

Meaning it would error for old players who aren't initialized because they joined before the mod was added.

**Comment by kaadmy** [comment]
Hm, I'll add a check so getting an achievement will automatically check+add player data to the table.

**Comment by kaadmy** [comment]
Okay, latest Git now has a failsafe so the crash won't happen, but achievements aren't migrated over to the new file.

**Comment by asl97** [comment]
I predict future issue report titled `achievement disappeared after updating`.

**Comment by kaadmy** [comment]
LOL :D
I'll add a notice in the forum post.
