### ISSUE TITLE
Player may spawn in dirt created by village

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#43]
If you're unlucky, you may spawn right in the middle of dirt which is created by a village.

How to reproduce:
* Use Minetest 0.4.15
* Use Pixture dec846e26507f14c30a35d16cc2fa70f967d8417
* Create world with seed 7 and mapgen v7
* Start game and wait for a few seconds for the village to generate

**Comment by kaadmy** [comment]
With the seed `7` there's 3 nearby villages but none inside me.. possibly a discrepancy in Minetest's PRNG?

**Comment by Wuzzy2** [comment]
Damn, I can't reproduce the village with the given seed as well.
But I'm sure the dirt comes from the village, not Minetest. That's because the village generated a few seconds after the basic landscape.

As soon as I find a reliable seed, I report back.

**Comment by kaadmy** [comment]
Okay.
I don't have too much control over the player spawning since Minetest auto spawns the player right now.
I could probably put in a custom on_spawn function for players that lifts them up so they're not in the ground, but this can't be fixed too easily since villages can generate at any time, not just at player spawn.
Minetest's default spawning algorithm also puts the player inside of trees sometimes, since it only accounts for the terrain and not structures.

**Comment by Wuzzy2** [comment]
You may not have control over the player spawn, but you have control over the first villge created. If you create the village much higher than ground level, it's logical the player gets buried.

Still, there is no easy way to fix this atm. Spawning clearly needs much, much better API support in Minetest, I agree.

**Comment by kaadmy** [comment]
I could just force villages to spawn >512m away from the static spawnpoint.

**Comment by kaadmy** [comment]
Also the seed `8` spawns a village about 50 feet away from you.

**Comment by kaadmy** [comment]
The seed `10` seems to spawn you in a village.
